### ISSUE TITLE
The wiki is missing

### ISSUE THREAD

**Issue by 0x5c** [lewysDavies/GriefPreventionFlags#7]
The wiki from the previous repo has not been migrated to this one.

**Comment by lewysDavies** [comment]
The wiki will not be migrated or maintained by choice

**Comment by 0x5c** [comment]
Is this to encourage people to not use this fork?

**Comment by lewysDavies** [comment]
I wont be changing it at all from Shane's wiki. ill link it in the read me

**Comment by lewysDavies** [comment]
Wiki removed and link in read-me added https://github.com/lewysDavies/GriefPreventionFlags/commit/d33fd2b6440595daebe3220d591cc1550262f0ed
